spring.application.name=Barbery-Times

spring.datasource.url=jdbc:postgresql://localhost:5432/barbery_times
spring.datasource.username=postgres
spring.datasource.password=shivansh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.flyway.enabled=true